targets:
  $default:
    builders:
      generators|annotations: # generators|annotations: Refers to the simple_generator builder when dealing with files annotated with annotations.
        enabled: true

builders:
  generators:
    target: ":generators" # Generator name
    import: "package:generators/generators.dart"
    builder_factories: ["generateJsonClass"] # Builder name(BuilderOption) this is a definition
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: source # directory of file save
    # applies_builders: ["source_gen|combining_builder"] 