targets:
  $default:
    builders:
      generators|redux_annotations:
        enabled: true

builders:
  generators:
    target: ":generators"
    import: "package:generators/generators.dart"
    builder_factories: ["generateReduxcode"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: source 
    # applies_builders: ["source_gen|combining_builder"] 